name: test-and-publish
on:
  push:
    branches:
      - develop

jobs:
  openergy:
    uses: openergy/ogithub-actions/.github/workflows/opypackage-standard-v05.yml@master
    with:
      install-eplus-2210: true
      make-doctest: true
      os-requirements: "['ubuntu-latest']"
      python-conda-requirement: ">=3.8,<3.13"
      python-versions: "['3.10', '3.11', '3.12']"

    secrets:
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
      PYPI_OPENERGY_PASSWORD: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
