name: test-and-publish
on:
  push:
    branches:
      - develop

# todo [CC]: manage latest mac and windows os tests
jobs:
  openergy:
    uses: openergy/ogithub-actions/.github/workflows/opypackage-standard-v03.yml@master
    with:
      install-eplus-2210: true
      publish-to-pypi: true

    secrets:
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
